import Head from 'next/head'
import Cover from './components/Cover'
import Formulario from './components/Formulario'
import Benefits from './components/Benefits'
import Footer from './components/Footer'
import HeaderGeneral from './components/Header'
import Gallery from './components/Gallery'

export default function Home() {

  return (
    <>
      <Head>
        <title>We Are Velier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <HeaderGeneral />
      <Cover />
      <div className='MobileItem'>
        <Benefits />
      </div>
      <Gallery />
      <Formulario />
      <Footer />
    </>
  )
}
