import Head from 'next/head'
import Cover from './components/Cover'
import Formulario from './components/Formulario'

export default function Home() {
  return (
    <>
      <Head>
        <title>We Are Velier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cover />
      <Formulario />
      <Formulario />
    </>
  )
}
