import { useRouter } from 'next/router';
import Head from 'next/head';
import Formulario from '../components/template/Formulario';
import Benefits from '../components/Benefits';
import CoverDentist from '../components/template/CoverDentist';
import Header from '../components/template/Header';
import Footer from '../components/template/Footer';
import Gallery from '../components/Gallery';
import LoveBar from '../components/template/LoveBar';
import Map from '../components/template/Map';
import Contacto from '../components/template/Contacto';

export default function DentistPage() {
  
  const router = useRouter();
  const { slug } = router.query;

  const title = slug ? slug.replace(/-/g, ' ') : 'Dentist';

  const username = title
  ? title.replace(/ /g, '').toLowerCase()
  : '';
  
  console.log(username)
  const initials = slug
  ? slug
      .split('-')
      .map(word => word.charAt(0))
      .join('')
  : '';

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Header logo={initials} />
      <CoverDentist title={title} />
      <Gallery />
      <LoveBar title={title} />
      <Formulario />
      {username && (
        <Contacto username={username} />
      )}
      <Footer logo={title} />
    </>
  );
}