import { useRouter } from 'next/router';
import Head from 'next/head';
import CoverDentist from '../components/template/CoverDentist';
import Formulario from '../components/Formulario';
import Benefits from '../components/Benefits';

export default function Dentista() {
  const router = useRouter();
  const { query } = router;

  // Obtén el parámetro "slug" de la URL
  const { slug } = query;

  // Genera el contenido del elemento h1 en función del parámetro "slug"
  const title = slug ? slug.replace(/-/g, ' ') : 'Dentist';

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      
      <h1>{title}</h1>
      <CoverDentist />
      <div className='MobileItem'>
        <Benefits />
      </div>
      <Formulario />
    </>
  );
}
